### ISSUE TITLE
Version 4.22

### ISSUE THREAD

**Issue by DarthSoul92** [sigtrapgames/VrTunnellingPro-UE4#1]
Hi! I've downloaded the latest version and copied the folder into my 4.22 project but everytime a try to open it a window appears with this message "The VRTunnellingPro plugin was desgined for build 4.20.0. Attempt to load it anyway?" So it doesn´t work. Has anyone had this problem?

**Comment by darbycostello** [comment]
Hi, thanks for downloading. Did you download the latest plugin directly from the Releases page, or have you cloned the master branch and copied the plugin folder into your 4.22 project?

**Comment by darbycostello** [comment]
That should fix your issue, just updated the VRTunnellingPro.uplugin file to 4.22. Thanks for your patience.

**Comment by DarthSoul92** [comment]
Hi again! I've downloaded the master branch with this new file but it still doesn´t work. When I try to open the project this window shows up: "The following modules are missing or built with a different engine version: VRTPUE VRTunnellingPro Would you like to rebuild them now?" I click Yes and it shows this error: "VRTPUE could not be compiled. Try rebuilding from source manually"
I don't know how to do this. Could you help?

**Comment by darbycostello** [comment]
The project is a full C++ UE4 project, so we strip the compiled binaries within the repo. So in order to run the project, one would need Visual Studio installed so that UE4 can rebuild those binaries and intermediate folders specific to your PC. However, rather than forcing you to download VS simply so you can check out the demo project, I have an alternative for you: I've built the full UE4.22 project at my end with all the binaries, then dropped a shareable link ([copied in here for your convenience](https://drive.google.com/open?id=1dHePgBieK9IGHRBB3Q35atPh0Zo04du3)) on the front page of the repo. This is compiled for Win64, which I'm assuming is your preferred platform. So you should be able to download this version of the project and run it without VS installed. Hope this helps :)

**Comment by DarthSoul92** [comment]
Thank you so much!!! :D

**Comment by jleaders** [comment]
Might we have 4.23 or 4.24 support published? Thanks!
